server:
  port: 8080

spring:
  application:
    name: careerquest

  config:
    import: optional:classpath:.env.properties

  datasource:
    url: jdbc:postgresql://ep-shy-silence-a1mfem0j-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_PmWaAo5CGg9Y
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    
springdoc:
  swagger-ui:
    path: /api-test

custom:
  jwt:
    secretKey: ${JWT_SECRET}